### ISSUE TITLE
Unable to Add Server (Field Validation for Server Name Broken)

### ISSUE THREAD

**Issue by zypherion** [frameset/klutter#1]
Trying to test out the app but it's given me an error when I try to add my home server. I enter the information requested but the validation on the "Server Name" field doesn't pass. It states I should enter a "valid email" in that field... For testing purposes I did but the error message remains.

I'm borderline suspect this is just phishing information.

**Comment by frameset** [comment]
The error message is a mistake on my part, and I have amended it.

As for the format of the server be sure to include protocol and do not
include a trailing slash. For example:

https://komga.example.com

**Comment by zypherion** [comment]
Perfect, it's working now that I added the protocol to the server name. I'll keep playing with it, but it looks super promising... Sorry for the phishing paranoia and thanks for the incredibly quick response!
